services:
  juice-shop:
    image: bkimminich/juice-shop
    container_name: juice-shop
    ports:
      - "3000:3000"
    restart: always

  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    container_name: zap
    depends_on:
      - juice-shop
    volumes:
      - ./zap:/zap/wrk
    entrypoint: >
     sh -c "
     echo 'Waiting for Juice Shop...' &&
      until curl -s http://juice-shop:3000 > /dev/null; do sleep 1; done &&
      echo 'Juice Shop is up! Starting FULL SCAN...' &&
      zap.sh -cmd -autorun /zap/wrk/zap.yaml
      "
