env:
  contexts:
    - name: "full-scan"
      urls:
        - "http://juice-shop:3000"

jobs:
  - type: spider
    parameters:
      url: "http://juice-shop:3000"
      maxChildren: 10
      maxDepth: 5
      maxDuration: 2

  - type: activeScan
    parameters:
      url: "http://juice-shop:3000"
      maxRuleDurationInMins: 1
      addQueryParam: true
      recurse: true

  - type: passiveScan-wait
    parameters:
      maxDuration: 2

  - type: report
    parameters:
      reportDir: "/zap/wrk"
      reportFile: "report.html"
      template: "traditional-html"
      reportTitle: "OWASP ZAP Full Scan Report"

  - type: report
    parameters:
      template: "traditional-xml"
      reportDir: "/zap/wrk"
      reportFile: "report.xml"

  - type: report
    parameters:
      template: "traditional-json"
      reportDir: "/zap/wrk"
      reportFile: "report.json"

  - type: report
    parameters:
      template: "traditional-md"
      reportDir: "/zap/wrk"
      reportFile: "report.md"
